// Konfigurasi Tailwind jika Anda masih menggunakan Tailwind via Script/CDN
window.tailwind = window.tailwind || {};
window.tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "primary-container": "#ffc107",
                "inverse-on-surface": "#fbefde",
                "on-tertiary": "#ffffff",
                "tertiary-container": "#ffbab3",
                "surface-container": "#f8ecdb",
                "surface-container-high": "#f2e7d6",
                "on-primary-fixed-variant": "#5b4300",
                "surface-variant": "#ece1d0",
                "surface-tint": "#785900",
                primary: "#785900",
                "surface-container-highest": "#ece1d0",
                "secondary-fixed-dim": "#91d78a",
                "on-background": "#201b11",
                tertiary: "#ba1a20",
                "surface-container-lowest": "#ffffff",
                outline: "#827660",
                "surface-dim": "#e4d9c8",
                "inverse-primary": "#fabd00",
                "on-secondary-container": "#307231",
                "on-primary-container": "#6d5100",
                "on-secondary-fixed": "#002203",
                "on-tertiary-container": "#ac0c18",
                "outline-variant": "#d4c5ab",
                "on-error": "#ffffff",
                "on-error-container": "#93000a",
                "on-tertiary-fixed-variant": "#930010",
                "on-tertiary-fixed": "#410003",
                "inverse-surface": "#363024",
                "error-container": "#ffdad6",
                "surface-container-low": "#fef2e1",
                surface: "#fff8f2",
                "on-primary-fixed": "#261a00",
                "on-surface-variant": "#4f4632",
                "on-secondary": "#ffffff",
                "on-secondary-fixed-variant": "#0c5216",
                "primary-fixed-dim": "#fabd00",
                "on-primary": "#ffffff",
                "surface-bright": "#fff8f2",
                "secondary-fixed": "#acf4a4",
                "tertiary-fixed-dim": "#ffb3ac",
                secondary: "#2a6b2c",
                "on-surface": "#201b11",
                "secondary-container": "#acf4a4",
                "primary-fixed": "#ffdf9e",
                "tertiary-fixed": "#ffdad6",
                error: "#ba1a1a",
                background: "#fff8f2",
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                full: "9999px",
            },
            spacing: {
                base: "4px",
                "margin-mobile": "20px",
                "margin-desktop": "64px",
                gutter: "24px",
                "column-count": "12",
            },
            fontFamily: {
                "label-md": ["Rubik"],
                "title-md": ["Rubik"],
                "body-lg": ["Rubik"],
                "headline-lg-mobile": ["Rubik"],
                "label-sm": ["Rubik"],
                "headline-lg": ["Rubik"],
                "display-lg": ["Rubik"],
                "body-md": ["Rubik"],
            },
            fontSize: {
                "label-md": [
                    "14px",
                    {
                        lineHeight: "20px",
                        letterSpacing: "0.01em",
                        fontWeight: "500",
                    },
                ],
                "title-md": ["20px", { lineHeight: "28px", fontWeight: "500" }],
                "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
                "headline-lg-mobile": [
                    "24px",
                    { lineHeight: "32px", fontWeight: "600" },
                ],
                "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
                "headline-lg": [
                    "32px",
                    { lineHeight: "40px", fontWeight: "600" },
                ],
                "display-lg": [
                    "48px",
                    {
                        lineHeight: "56px",
                        letterSpacing: "-0.02em",
                        fontWeight: "700",
                    },
                ],
                "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
            },
        },
    },
};
